### ISSUE TITLE
have nicer names for the applications

### ISSUE THREAD

**Issue by sabbour** [bradygmsft/phippy-demo#4]
I liked naming the `goapp` as `lighthouse`.

**Reasoning:**
Keeping with the marine theme of everything Kubernetes, the app is probing the sea for containers and announcing their presence.

Could we use similar names for the other apps, depending on what they will do as part of the demo?

**Comment by bradygmsft** [comment]
i love the idea. realistically most of them don't do a whole lot, they're just apps that show up in a place in the UI. there's no end-to-end scenario here where one app does a thing, another app takes the thing and does the next thing, and so on. 

if we should do things in a way that each app "has a purpose," i can definitely think about that as i'm building them out. **i love the idea** though, of having the end-to-end theme, and think it works quite well. i was more imagining the other characters, like the .net bot and maybe a few specifically-themed Brady sloths (and no, i didn't invent Brady, i'm not being self-serving here, it's a coincidence, i swear!) showing up as "friends of phippy in the kubernetes sea," but if we want the app to actually do something so each character has a role, we can talk about that, for sure. i love it, but it may prove significantly more substantial and may require more creative design investments. 

open to ideas - let's sync!
